"""Auto-generate a PR description from the agent's trajectory."""

from __future__ import annotations

from app.agent.trajectory import Trajectory
from app.agent.types import AgentStatus


def build_pr_description(
    *,
    issue_number: int,
    issue_title: str,
    trajectory: Trajectory,
    status: AgentStatus,
    baseline_tests: dict | None,
    final_tests: dict | None,
    model: str,
    duration_ms: int,
    dashboard_url: str,
    run_id: str,
) -> str:
    steps = trajectory.steps
    edited = sorted(
        {
            s.action.args.get("path")
            for s in steps
            if s.action and s.action.tool in ("edit_file", "create_file") and s.action.args.get("path")
        }
    )
    root_cause = _infer_root_cause(trajectory)

    changes = "\n".join(f"- Modified `{p}`" for p in edited) or "- (no file changes recorded)"
    final = final_tests or {}
    base = baseline_tests or {}
    test_line = (
        f"{final.get('passed', '?')} passing / {final.get('failed', '?')} failing"
        if final
        else "not recorded"
    )
    duration_s = round(duration_ms / 1000, 1)

    key_decisions = _key_decisions(trajectory)

    return f"""## AutoSWE Fix for #{issue_number}

### Issue
{issue_title}

### Root Cause
{root_cause}

### Changes Made
{changes}

### Reasoning Trace
The agent took {len(steps)} steps to work this issue. Key decisions:
{key_decisions}

[View full reasoning trace →]({dashboard_url}/runs/{run_id})

### Test Results
- Baseline: {base.get('passed', '?')} passing / {base.get('failed', '?')} failing
- After fix: {test_line}

---
_Generated by AutoSWE using {model} • {len(steps)} steps • {duration_s}s • status: {status.value}_
"""


def _infer_root_cause(trajectory: Trajectory) -> str:
    # Use the thought from the step just before the first edit, if any.
    steps = trajectory.steps
    for i, s in enumerate(steps):
        if s.action and s.action.tool in ("edit_file", "create_file"):
            if i > 0 and steps[i - 1].thought:
                return steps[i - 1].thought
            if s.thought:
                return s.thought
    if trajectory.summary:
        return trajectory.summary
    return "See the reasoning trace for the agent's root-cause analysis."


def _key_decisions(trajectory: Trajectory, limit: int = 5) -> str:
    lines = []
    n = 1
    for s in trajectory.steps:
        if not s.action:
            continue
        if s.action.tool in ("search_code", "edit_file", "create_file", "run_tests", "submit_solution"):
            summary = s.thought.split("\n")[0][:140] if s.thought else s.action.tool
            lines.append(f"{n}. `{s.action.tool}` — {summary}")
            n += 1
        if len(lines) >= limit:
            break
    return "\n".join(lines) or "1. See full trace."
